### ISSUE TITLE
How to use this tool?

### ISSUE THREAD

**Issue by pconerly** [prismicio/wp2prismicio#1]
Hi--- I know you probably just wrote this as a private tool to use, but you're the first google result for "prismic.io wordpress importer".  :)  How would I run this tool?  I'm also going to be converting my company's wordpress blog content to prismic in a couple weeks.

We're guessing that we'd just change the file at this line: https://github.com/prismicio/wp2prismicio/blob/master/src/main/scala/main.scala#L239 and run main.scala ?

**Comment by erwan** [comment]
Hi,

Thank you for your interest in prismic.io!

It's an sbt project, and yes you just have to change this line. However to use the zip that will be produced, you need the import feature that is not publicly released yet.

Please open a support ticket if you want to discuss about your project and the import feature availability.
